theme: minima
title: Scientific and Enterprise Development
author: Adrian Dante Garcia
email: adriandantegarcia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is concerned with Scientific Programming, Enterprise Development, 
  Python, Artificial Intelligence, Machine Learning, Python, Java, Jakarta EE.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  agarcia-github # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
